export const ROLES = {
  DELETE_INSTITUTION: 'ROLE_delete_institution',
  CREATE_ROLE: 'ROLE_create_role',
  READ_PRIVILEGES: 'ROLE_read_privileges',
  READ_REPORTS: 'ROLE_read_reports',
  DELETE_COMMENT: 'ROLE_delete_comment',
  READ_ROLES: 'ROLE_read_roles',
  DELETE_USER: 'ROLE_delete_user',
  UPDATE_PRIVILEGE: 'ROLE_update_privilege',
  UPDATE_ROLE: 'ROLE_update_role',
  CREATE_PRIVILEGE: 'ROLE_create_privilege',
  UPDATE_POST: 'ROLE_update_post',
  READ_LOGS: 'ROLE_read_logs',
  CREATE_INSTITUTION: 'ROLE_create_institution',
  UPDATE_USER: 'ROLE_update_user',
  CREATE_COMMENT: 'ROLE_create_comment',
  CREATE_USER: 'ROLE_create_user',
  READ_POST: 'ROLE_read_post',
  DELETE_ROLE: 'ROLE_delete_role',
  LIKE_POST: 'ROLE_like_post',
  READ_MESSAGES: 'ROLE_read_messages',
  READ_POSTS: 'ROLE_read_posts',
  UPDATE_INSTITUTION: 'ROLE_update_institution',
  DELETE_PRIVILEGE: 'ROLE_delete_privilege',
  READ_INSTITUTIONS: 'ROLE_read_institutions',
  READ_USER: 'ROLE_read_user',
  READ_USERS: 'ROLE_read_users',
  READ_COMMENTS: 'ROLE_read_comments',
  DELETE_POST: 'ROLE_delete_post',
  READ_INSTITUTION: 'ROLE_read_institution',
  UNLIKE_POST: 'ROLE_unlike_post',
  READ_ROLE: 'ROLE_read_role',
  CREATE_POST: 'ROLE_create_post',
  SEND_MESSAGE: 'ROLE_send_message',
  READ_PRIVILEGE: 'ROLE_read_privilege',
};

export const ROLE_DESCRIPTIONS = {
  [ROLES.DELETE_INSTITUTION]: 'Delete Institution',
  [ROLES.CREATE_ROLE]: 'Create Role',
  [ROLES.READ_PRIVILEGES]: 'Read Privileges',
  [ROLES.READ_REPORTS]: 'Read Reports',
  [ROLES.DELETE_COMMENT]: 'Delete Comment',
  [ROLES.READ_ROLES]: 'Read Roles',
  [ROLES.DELETE_USER]: 'Delete User',
  [ROLES.UPDATE_PRIVILEGE]: 'Update Privilege',
  [ROLES.UPDATE_ROLE]: 'Update Role',
  [ROLES.CREATE_PRIVILEGE]: 'Create Privilege',
  [ROLES.UPDATE_POST]: 'Update Post',
  [ROLES.READ_LOGS]: 'Read Logs',
  [ROLES.CREATE_INSTITUTION]: 'Create Institution',
  [ROLES.UPDATE_USER]: 'Update User',
  [ROLES.CREATE_COMMENT]: 'Create Comment',
  [ROLES.CREATE_USER]: 'Create User',
  [ROLES.READ_POST]: 'Read Post',
  [ROLES.DELETE_ROLE]: 'Delete Role',
  [ROLES.LIKE_POST]: 'Like Post',
  [ROLES.READ_MESSAGES]: 'Read Messages',
  [ROLES.READ_POSTS]: 'Read Posts',
  [ROLES.UPDATE_INSTITUTION]: 'Update Institution',
  [ROLES.DELETE_PRIVILEGE]: 'Delete Privilege',
  [ROLES.READ_INSTITUTIONS]: 'Read Institutions',
  [ROLES.READ_USER]: 'Read User',
  [ROLES.READ_USERS]: 'Read Users',
  [ROLES.READ_COMMENTS]: 'Read Comments',
  [ROLES.DELETE_POST]: 'Delete Post',
  [ROLES.READ_INSTITUTION]: 'Read Institution',
  [ROLES.UNLIKE_POST]: 'Unlike Post',
  [ROLES.READ_ROLE]: 'Read Role',
  [ROLES.CREATE_POST]: 'Create Post',
  [ROLES.SEND_MESSAGE]: 'Send Message',
  [ROLES.READ_PRIVILEGE]: 'Read Privilege',
};
